### PR TITLE
Add an ENTRYPOINT to dockerd-entrypoint

### PR DESCRIPTION
**Pull request by sdake**
DIND includes a dockerd-entrypoint.sh script. Use that directly for
ENTRYPOINT.  Next iteration will include authentication when running
in Prow.

### CODE REVIEW

**Comment by howardjohn** [comment]
How long does this take to run? It may not be great to run `dockerd` every time I run `make xyz` locally

**Comment by sdake** [comment]
dockerd is only run if a docker command is detected in the command line.

**Comment by howardjohn** [comment]
oh then I don't think this would work.. unless it knows `make e2e` runs docker but `make test` doesnt

**Comment by howardjohn** [comment]
Also I think the kubernetes command field overrides the docker images ENTRYPOINT

**Comment by sdake** [comment]
fair, as I mentioned in slack, this is simply a test to see how entrypoint behaves in prow.  Perhaps an invalid test given the above conversation.

Cheers
-steve

**Pull request merged**
