### PR TITLE
[release-1.7] Bump golang

### PR DESCRIPTION
**Pull request by jwendell**

### CODE REVIEW

**Comment by ericvn** [comment]
It looks like the new docker image is now available.

**Comment by jwendell** [comment]
@ericvn 
```
$ docker pull golang:1.14.7
1.14.7: Pulling from library/golang
no matching manifest for linux/amd64 in the manifest list entries
```

**Comment by ericvn** [comment]
And is there a reason to have it in 1.7 before master? Maybe to get into the next build quicker. Should cherrypick to master.

**Comment by jwendell** [comment]
> And is there a reason to have it in 1.7 before master? Maybe to get into the next build quicker. Should cherrypick to master.

cherrypick not always work. I thought they follow different paths. I'm happy to try it as soon as it merges on 1.7.

**Pull request closed without merging**
