### PR TITLE
go 1.20

### PR DESCRIPTION
**Pull request by jacob-delgado**

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]
yay

**Review by ericvn — APPROVED** [review]

**Comment by howardjohn** [comment]
quic-go needs to be bumped to master first (or they need to do a new release)

/hold

**Comment by jacob-delgado** [comment]
Need to track https://github.com/quic-go/quic-go/issues/3686 and https://github.com/istio/istio/issues/42347

**Comment by jacob-delgado** [comment]
https://github.com/istio/istio/pull/43101 was merged so I'm removing the label. The changes are also in for 1.17

**Pull request merged**
