### PR TITLE
[Cherrypick]Install the latest gcloud tool and its beta components in the build-tools image

### PR DESCRIPTION
**Pull request by chizhg**
Install the latest gcloud tool and its beta components in the build-tools image

### CODE REVIEW

**Review by jwendell — COMMENTED** [review]
Why do we need this in 1.7?

**Comment by chizhg** [comment]
Sorry for the missing background - this PR is a cherrypick of https://github.com/istio/tools/pull/1307 since we are adding some jobs running on GKE on GCP for all releases, which requires the latest version of `gcloud`. I've also created cherrypicking PRs to release-1.7 and release-1.8, and they have been merged.

**Comment by chizhg** [comment]
- 1.6: https://github.com/istio/tools/pull/1310
- 1.8: https://github.com/istio/tools/pull/1312

**Comment by chizhg** [comment]
@jwendell could you take a second look at this PR and approve if it looks good to you? Thanks!

**Review by jwendell — APPROVED** [review]

**Pull request merged**
