### PR TITLE
Automated verification of security in multicluster

### PR DESCRIPTION
**Pull request by lei-tang**
Automated verification of security in multicluster, which covers:
- Authentication policies (strict mTLS and auto mTLS) and certs.
- Authorization policies.

### CODE REVIEW

**Comment by lei-tang** [comment]
@howardjohn We plan the testing of security for multicluster to be consisted of 1) scripts based automated tests. 2) golang based integration tests. 
This PR is for task 1. 
The integration tests in istio/istio for security in multicluster mentioned in your comment belong to the task 2 and they will be added later.

**Comment by howardjohn** [comment]
What is the point of task 1? Why not just do task 2

**Comment by lei-tang** [comment]
Both task 1 and task 2 can be used to verify the security in multicluster (one uses shell scripts while the other uses the golang). The golang based implementation takes longer to implement and due to time constraints of ASM 1.6 release, security team decides to first implement the task 1 and implement task 2 later.

**Comment by howardjohn** [comment]
If you want to do something for a private distribution of Istio you are free to do so on your own. In my opinion this does not meet the bar for testing quality we expect in Istio - I would strongly prefer we only have the golang implementation in istio, even if it takes more time.

Manual testing (and that is what this is - a script does not make it automated if it's not run in CI) is not really acceptable at this stage in the project in my opinion. If it's not automated it's not tested.

**Comment by lei-tang** [comment]
The scripts in this repository (e.g., Istio performance tests, Istio upgrade tests) can be added to CI to run automatically. Similarly, the scripts in this PR can use the same approach to run with CI, which can be added as a separate PR.
We agree golang-based tests in the istio/istio repository are also needed and security team will add them later. We need both types of tests (scripts-based and golang-based) and they are not exclusive to each other.

**Comment by howardjohn** [comment]
> they are not exclusive to each other

Why? There is not a single benefit of this test compared to the golang version that I am aware of, aside from the fact you have already implemented the script one. It does not make any sense to have both versions around if they test the same thing

If we have invested all of the time you spent on this we could be done with the golang tests

**Comment by lei-tang** [comment]
The tests in this repository (e.g., Istio performance tests, Istio upgrade tests) are implemented using scripts and the script-based implementation has its own benefits, such as taking less time to implement, easier to run and modify, and easier to understand as the commands (e.g., kubectl, curl, etc) are directly executed in scripts.
The scripts-based tests for security in multi-cluster have been discussed in ASM 1.6 plannings and you have added similar comments to those discussions, which have been replied before.

**Comment by howardjohn** [comment]
What happens in ASM (a Google product) and Istio (an open source project) are not related. And my comments regarding ASM plans do not apply to OSS.

The upgrade tests are a horrible example as they have missed every single upgrade bug, and have proven to not be useful. The performance tests are completely unique - they run forever at scales far beyond what can run in CI (200 vcpu clusters).

What you are adding is just a normal test, no different really than any other integration test we currently have. As such, I would expect it to follow the existing patterns for integration tests. Any other pattern, as done here, should have a compelling justification - taking longer to implement is not convincing.

**Comment by lei-tang** [comment]
Like you mentioned for Istio performance tests, other benefits of the script-based tests include that they are easier to scale and they can run longer time than does CI. This PR currently tests security in two clusters but follow-up PRs can extend it to test security in larger number of clusters (e.g., 100) that are beyond the CI can handle.
The fact that this PR can be extended in follow-up PRs to test security in larger number of clusters and run longer time are compelling justifications for merging this PR, which will be the foundation for its future extensions for testing security in multicluster.

**Comment by nmittler** [comment]
@lei-tang this PR needs to be changed to be a proper golang test using the integration test framework, the scripts are not sufficient. If you want separate scripts for other types of testing, that's fine ... you can write your code in such a way that there is shared library code and you can have a separate test main.

**Comment by lei-tang** [comment]
@nmittler We will add golang based integration tests to the istio/istio repository in separate PRs. This PR is for the script-based tests and uses the same implementation approach as other script-based performance tests (e.g., https://github.com/istio/tools/tree/master/perf/security). We need both golang based integration tests and script-based tests (e.g., for performance testing).

**Comment by howardjohn** [comment]
@lei-tang lets take a step back

* Currently, the golang tests have 100s of test of the form "apply istio config, send some requests and validate"
* You are attempting to add a new test of the form "apply istio config, send some requests and validate"

Your test is *not* unique - it is just like these other tests. Its actually almost identical to TestReachability really. This means one of two things:

1. Either every golang test is doing it wrong, and they should instead be implemented like this.
2. This test is doing it wrong, and it should be implemented like the other ones.

Having two different ways of testing similar things is not acceptable. We should have all of our tests implemented in a consistent way. Therefor, if you would like to do this, you will need to convince the community that this approach to testing is the correct one for all of the existing tests like this.

**Comment by lei-tang** [comment]
@howardjohn Yes, golang-based tests and script-based tests (e.g., the performance tests in this repository) are testing similar things. However, unlike golang-based integration tests that run on CI clusters for a shorter time, the script-based tests in this repository can run in larger clusters and run longer time for performance testing. We need both types of tests and this repository hosts the script-based tests.

**Comment by howardjohn** [comment]
@lei-tang if that is the case, do you think we should also take all of the existing golang tests and add them here?

If you genuinely want to run these "at scale", then it would be a better investment to write the test using the golang test framework and allow those tests to be run in the way you want. You mentioned you want to run with many clusters, this is already possible today in the framework. You also mentioned you want to run them continuously - if we you want this, you can add a mode to the golang test framework that does the tests continuously rather than the current model where we just run once and exit.

If you still disagree I recommend escalating the issue to T&R or TOC, as I will not approve this.

**Comment by nmittler** [comment]
I strongly agree with @howardjohn here. These are verification tests, not performance tests. Performance tests are another animal altogether. The fact that they are currently script-based is unfortunate and that will hopefully change in the future.

All verification (i.e. integration/e2e) tests in Istio are in golang, and this needs to be as well. If you want to write code that you can use for both, you'll have to do it in golang and call it from your performance test script.

**Comment by lei-tang** [comment]
- This PR verifies security in multicluster but follow-up PRs can extend it to conduct performance testing for security in multicluster (using the same approach as https://github.com/istio/tools/tree/master/perf/security). Before the golang-based integration tests in the istio/istio repository are added for security in multicluster, the scripts in this PR can be used to verify security in multicluster.

- This PR is created on the istio/tools repository, in which tests are implemented using shell scripts. The golang-based integration tests are in a different repository (i.e., the istio/istio repository). We will add golang-based integration tests for security in multicluster to the istio/istio repository, which is a different task.

- Regarding to the comment "If you want to write code that you can use for both, you'll have to do it in golang and call it from your performance test script.", this PR is on the istio/tools repository and it uses the same script-based implementation approach as other tests in this repository. AFAIK, there is no performance tests in this repository uses the approach of "do it in golang and call it from your performance test script."
This PR is only for the istio/tools repository, not for the istio/istio repository. For the istio/istio repository, the golang-based integration tests for security in multicluster will be added as a different task.

- I have a few questions unrelated to this PR but related to the multicluster integration tests in the istio/istio repository. 
Question 1: Is the the multicluster test framework in the istio/istio repository completed? If not, when will it be completed?
Question 2: Are there multicluster integration tests in the istio/istio repository that test foundamentals of multicluster such as verifying cross-cluster load balancing in multicluster, and deploying an Istio policy and verifying the policy is effective in multicluster? If there are, can you provide URLs to these multicluster integration tests in the istio/istio repository?

**Comment by howardjohn** [comment]
Lei, as mentioned above I strongly believe this is not a good idea to merge, as does Nate. Rehashing that here will not help anyone. If you want to move forward with this please escalate to T&R or TOC.

**Comment by lei-tang** [comment]
> Lei, as mentioned above I strongly believe this is not a good idea to merge, as does Nate. Rehashing that here will not help anyone. If you want to move forward with this please escalate to T&R or TOC.

John, review comments are always welcome and appreciated by me and I try to reply each review comment. The PR is public commentable and there may be viewers of the PR want to participate the discussions here. If you think the discussions here are not helpful to you, you may ignore them.

**Comment by nmittler** [comment]
@lei-tang 

> John, review comments are always welcome and appreciated by me and I try to reply each review comment. The PR is public commentable and there may be viewers of the PR want to participate the discussions here. If you think the discussions here are not helpful to you, you may ignore them.

I'm not sure this addresses the overarching point that @howardjohn is making. There is clearly a strong fundamental objection to this PR and simply trying to force it through is not a path forward. The way I see it you have two possible ways of resolving this:

1. Make proper golang tests based on the test framework, as John and I are suggesting
2. Escalate to the TOC

If you submit this as-is, I guarantee that this will become a topic at the next TOC. It'll just be a less pleasant conversation.

**Comment by lei-tang** [comment]
> @lei-tang
> 
> > John, review comments are always welcome and appreciated by me and I try to reply each review comment. The PR is public commentable and there may be viewers of the PR want to participate the discussions here. If you think the discussions here are not helpful to you, you may ignore them.
> 
> I'm not sure this addresses the overarching point that @howardjohn is making. There is clearly a strong fundamental objection to this PR and simply trying to force it through is not a path forward. The way I see it you have two possible ways of resolving this:
> 
> 1. Make proper golang tests based on the test framework, as John and I are suggesting
> 2. Escalate to the TOC
> 
> If you submit this as-is, I guarantee that this will become a topic at the next TOC. It'll just be a less pleasant conversation.

@nmittler First of all, I appreciate and respect review comments (including objections) and I do not try to force a PR through (I am a believer that every PR must be properly reviewed and approved before it can be merged). As there are objections to this PR from reviewers, I am fine with not merging this PR.

Seond, I have a few questions related to the golang-based multicluster integration tests in the istio/istio repository.
Question 1: Is the golang-based multicluster test framework in the istio/istio repository completed? If not, when will it be completed?
Question 2: Are there multicluster integration tests in the istio/istio repository that test foundamentals of multicluster such as verifying cross-cluster load balancing in multicluster, and deploying an Istio policy and verifying the policy is effective in multicluster? If there are, can you provide URLs to these multicluster integration tests in the istio/istio repository?

**Comment by howardjohn** [comment]
> Question 1: Is the golang-based multicluster test framework in the
istio/istio repository completed? If not, when will it be completed?

I am not sure anything is ever "complete"... but its certainly usable and
in use today.

> Question 2

Yes, see
https://github.com/istio/istio/tree/99b67ebd08815508e352970a67e49f226eb5e971/tests/integration/multicluster

Please note, one of the core features of the multicluster stuff is that we
don't need special tests for multi and single cluster. You can just write
one test, and it can run in any environment. See
https://github.com/istio/istio/pull/24549 for example, making the pilot
tests support multiple clusters.

What I would imagine this looks like for this PR is for you to add a test
case to the existing TestReachability to add AuthorizationPolicy (today its
just authn). Then another PR can make that test multicluster compatible.
That way we test not only what is in this PR, but *all* existing security
reachability tests in multicluster. I suggest you sync up with Steven on
this as he may have more context than I do

**Comment by lei-tang** [comment]
Thanks! Since I will be OOO starting next week, other team members will work on the golang-based integration tests for security.

**Comment by jacob-delgado** [comment]
This PR is over a year old with no progress. Closing. Feel free to reopen it if you want to make changes.

**Pull request closed without merging**
