### PR TITLE
Release Notes Tooling

### PR DESCRIPTION
**Pull request by brian-avery**
This tooling will be used to generate release notes for Istio. This PR is to get the conversation going on style. The code is messy and I am working on cleaning it up as well as implementing the list below. 

Missing: 
* Need to better formulate parsing of templates
* Templates should allow specifying the format that notes should be displayed in. 
* Templates need to be better filled out. 
* Can't currently diff across branches. This will be needed once we have more than one release we are comparing.

### CODE REVIEW

**Comment by brian-avery** [comment]
Part of #23622

**Comment by brian-avery** [comment]
Removing the WIP on here. I will continue to work on this and evolve this for future PRs, but the 1.7 release is coming up and it would be nice to have the initial pass in the tree before we generate the release/upgrade notes.

**Comment by jwendell** [comment]
I have no idea why GH is not complaining about merge conflicts. The lint failures are already fixed in master...

**Comment by brian-avery** [comment]
Looks like I messed up the rebase.

**Comment by brian-avery** [comment]
@jwendell removed and squashed. This PR fixed those linter errors as well since they caused this PR to fail, but it looks like they were fixed elsewhere since this PR was opened.

**Comment by brian-avery** [comment]
Added a header to the template. The linter for tools is stricter than the linter for istio.io, causing this to fail here, but not there.

**Pull request merged**
