### PR TITLE
Update web site tooling.

### PR DESCRIPTION
**Pull request by geeknoid**

### CODE REVIEW

**Comment by howardjohn** [comment]
I am not sure how somehow the containers presubmit test takes 2hrs but the postsubmit took only like 46 minutes... it should be identical expect it is given MORE cpu than before

**Comment by howardjohn** [comment]
I am rerunning an old postsubmit to see if somehow I broke things or if docker randomly got slower

**Comment by geeknoid** [comment]
The job just timed out, so trying again...

/retest

**Comment by howardjohn** [comment]
/test containers-test_tools

The last one ran with the old build tools image still.. hopefully this picks up the changes

**Comment by howardjohn** [comment]
/test containers-test_tools

not sure I can force it to rerun while it's still running, may need to wait

**Pull request merged**
