### PR TITLE
[perf/benchmark] Adds graph.py visualization script

### PR DESCRIPTION
**Pull request by askmeegs**
- Adds a script (`runner/graph.py`) to visualize Istio data plane performance in a [Bokeh.js](https://bokeh.pydata.org/en/latest/) chart.  
- `runner/Pipfile` -- standardizes all benchmark scripts on Python3, lists all dependencies for `runner.py`, `fortio.py`, and `graph.py` 
- updates `README.md`: extend instructions for how to perform Istio data plane benchmarking

**Note**: branches off #157 for `nomixer` support. 

Example graph (screenshots/bokeh-screenshot): 
bokeh-screenshot

### CODE REVIEW

**Comment by mandarjog** [comment]
@askmeegs megan you have some random files from another PR in your commit. 
You should rebase on top of master.

**Comment by askmeegs** [comment]
@mandarjog other files are from your #157 to update mesh config (nomixer), so I can either rebase from master or wait for your PR to merge.

**Comment by ldemailly** [comment]
side note: reminder that fortio for instance already has built in graphing; eg
https://fortio.istio.io/?s=qps_max-ingress

**Comment by askmeegs** [comment]
@ldemailly yes -- the reason for creating the graph.py script was because we wanted to be able to combine both prometheus metrics (memory and CPU) and fortio metrics (latency) into the same style of chart, that can be easily embedded into the Istio docs / blog posts.

**Comment by mandarjog** [comment]
@askmeegs can you remove the prometheus file you have erroneously added here?
Otherwise let's get this in. It has other changes too which are stuck in other PRs.

**Pull request merged**
