### PR TITLE
add build dependencies for ebpf

### PR DESCRIPTION
**Pull request by irisdingbj**
below dependencies are added:
 clang 
 llvm 
libbpf-dev

Image side 
gcr.io/istio-testing/build-tools            master-051322f0945741253e6fb17ebd65e0f8d81341ad          15d9cf7025ca       4.95GB

gcr.io/istio-testing/build-tools            master-2023-02-17T14-56-30-amd64                         0fec7cd75115       5.23GB

less than 300MB increase

### CODE REVIEW

**Review by kyessenov — CHANGES_REQUESTED** [review]
There's no need for llvm as it's already needed by envoy.

**Review by kyessenov — CHANGES_REQUESTED** [review]
(forgot to request)

**Comment by irisdingbj** [comment]
> There's no need for llvm as it's already needed by envoy.

Thanks @kyessenov for the review.  Currently only `build-tools-proxy`  has llvm.  The one used to build istio `build-tools` does not have llvm. So we need to add it.   Some failure log due to lack of this dependendy is:

```
Error: exec: "llvm-strip": executable file not found in $PATH

```

**Comment by ericvn** [comment]
I'm not a big fan of adding more and more to the build-tools, but I don't know that we have a good way to use different images at present. Need to look into that some more. Maybe we can break the C and Rust portions out at some point.

**Review by ericvn — APPROVED** [review]

**Comment by ericvn** [comment]
/test containers-test-arm64

Both of the last two failed on bazellisk, but trying manually it worked.

**Pull request merged**
