### PR TITLE
Add missing protocol mode setting from configs/istio/none_tcp/latency.yaml

### PR DESCRIPTION
**Pull request by daisy-ycguo**

### CODE REVIEW

**Comment by daisy-ycguo** [comment]
@carolynhu Hi, will you help to check if `protocol_mode: tcp` in [configs/istio/none_tcp/cpu_mem.yaml](https://github.com/istio/tools/blob/master/perf/benchmark/configs/istio/none_tcp/cpu_mem.yaml#L23) is a wrong setting ? I checked the config files for `none` and `none_tcp`. I found `configs/istio/none_tcp/cpu_mem.yaml` is almost same as `configs/istio/none/cpu_mem.yaml`, while `configs/istio/none_tcp/lantency.yaml` doesn't contain this setting. So I guess the setting `protocol_mode: tcp` in `none_tcp` shall be removed, in order to be consistent with the `lantency.yaml`.

If I'm wrong, feel free to close this PR. Thank you.

**Comment by carolynhu** [comment]
Hi @daisy-ycguo protocol_mode should be required for none_tcp latency.yaml. could you please revert your change for cpu_mem.yaml, but add a protocol_mode field in the latency.yaml instead. Thanks!

**Review by carolynhu — COMMENTED** [review]
Hi @daisy-ycguo protocol_mode should be required for none_tcp, could you please revert your change for cpu_mem.yaml, but add a `protocol_mode: tcp` field in the latency.yaml instead? thanks!

**Comment by daisy-ycguo** [comment]
> Hi @daisy-ycguo protocol_mode should be required for none_tcp, could you please revert your change for cpu_mem.yaml, but add a `protocol_mode: tcp` field in the latency.yaml instead? thanks!

Thank you for the information. I updated according to your comments.

**Review by carolynhu — APPROVED** [review]

**Pull request merged**
