### PR TITLE
implement regression pattern graph

### PR DESCRIPTION
**Pull request by carolynhu**
Here is the effect picture:
Screen Shot 2019-12-16 at 7 08 50 PM

### CODE REVIEW

**Comment by howardjohn** [comment]
what is on the y axis?

**Comment by carolynhu** [comment]
@howardjohn y axis is (mixer_mode_number - baseline)

**Comment by howardjohn** [comment]
oh both minus baseline, i see. Can you out units? and maybe change it from "both-baseline" to "both" and make the title "additional latency" or something?

**Comment by howardjohn** [comment]
And probably instead of 7000 (microseconds?) it should be 7ms,which is more comment latency measurement #

**Comment by howardjohn** [comment]
is v2 missing in some days expected?

**Comment by carolynhu** [comment]
yes, this the real data for 1.4, v2 is missing for someday.

**Comment by carolynhu** [comment]
sure, I will update this PR according to your comments.

**Comment by howardjohn** [comment]
Is it supposed to be missing though?

**Comment by carolynhu** [comment]
I don't think so ... maybe those days pipeline has failures on those tests. Let me check.

**Comment by richardwxn** [comment]
FYI, there is an issue querying prom api for past couple days, created an issue to track here: https://github.com/istio/istio/issues/19594

**Comment by carolynhu** [comment]
@howardjohn address all comments, please take another look.

**Pull request merged**
