### PR TITLE
[release-1.6] Add recent perf benchmark test changes of master

### PR DESCRIPTION
**Pull request by carolynhu**
Make perf test run against release-1.6

This PR is to cherry-pick all recent tools repo master branch Perf benchmark related PRs.

### CODE REVIEW

**Comment by carolynhu** [comment]
Put on hold, I need to manually verify this work.

**Comment by brian-avery** [comment]
@carolynhu should this be merged into master first?

**Comment by carolynhu** [comment]
Verified this change locally, it runs well.

**Comment by carolynhu** [comment]
> @carolynhu should this be merged into master first?

This PR is actually cherry-pick of all the recent master changes related to performance tests. Since those actual PRs are hard to cherry-pick, there are lots of conflicts need to be resolved. I just make those changes in one PR manually.

**Comment by carolynhu** [comment]
@brian-avery This PR is ready to merged to release-1.6.

**Comment by carolynhu** [comment]
benchmark_check_tools_release-1.6 presubmit job is removed from istio/test-infra, we can ignore that.

**Comment by brian-avery** [comment]
@carolynhu Please add the issues in Master to the description.

**Comment by carolynhu** [comment]
@brian-avery @jacob-delgado this PR needs to be merged asap, since I need to gather Istio performance data for release-1.6 to publish. Thanks!

**Comment by carolynhu** [comment]
> benchmark_check_tools_release-1.6 presubmit job is removed from istio/test-infra, we can ignore that.

Here is the latest tools/master benchmark_check_tools job run and it passed: https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_tools/937/benchmark_check_tools/111/build-log.txt

which includes all the changes I made in this PR.

**Comment by jacob-delgado** [comment]
cc @carolynhu Approved. Links to the original PRs are still much appreciated in comments.

**Comment by carolynhu** [comment]
Yes, sure let me do it!

**Comment by brian-avery** [comment]
Thanks @carolynhu

**Comment by carolynhu** [comment]
For later perf-benchmark related changes cherry-pick to release-1.6 should be the PR after https://github.com/istio/tools/pull/937

This PR includes master PRs of the followings (only those perf benchmark related changes):
https://github.com/istio/tools/pull/856
https://github.com/istio/tools/pull/866
https://github.com/istio/tools/pull/842
https://github.com/istio/tools/pull/879
https://github.com/istio/tools/pull/864
https://github.com/istio/tools/pull/883
https://github.com/istio/tools/pull/885
https://github.com/istio/tools/pull/886
https://github.com/istio/tools/pull/891
https://github.com/istio/tools/pull/896
https://github.com/istio/tools/pull/692
https://github.com/istio/tools/pull/913
https://github.com/istio/tools/pull/918
https://github.com/istio/tools/pull/921
https://github.com/istio/tools/pull/919
https://github.com/istio/tools/pull/927
https://github.com/istio/tools/pull/929
https://github.com/istio/tools/pull/933
https://github.com/istio/tools/pull/937

**Pull request merged**
