### PR TITLE
whitelist modules for k/t-i bump

### PR DESCRIPTION
**Pull request by clarketm**
for: https://github.com/istio/test-infra/pull/2447

### CODE REVIEW

**Comment by howardjohn** [comment]
Actually I think this is from common-files?

**Comment by howardjohn** [comment]
Also we may want to add a comment about what license is used

**Comment by clarketm** [comment]
> > github.com/otiai10/curr uses a DWTFYWTP license (annoyingly)
> 
> I think this is a banned license



> Actually I think this is from common-files?

Thanks. Yes, wrong repo.

**Comment by clarketm** [comment]
> > github.com/otiai10/curr uses a DWTFYWTP license (annoyingly)
> 
> I think this is a banned license

In this case what is the proper course of action? This PR: https://github.com/istio/test-infra/pull/2447 has been stuck for a week due to license issues

**Comment by howardjohn** [comment]
Can we drop the dependency somehow? I don't think we can whitelist a banned license, it should be used only for when the tool is wrong

**Pull request closed without merging**
