### PR TITLE
Allow dry run for build tools

### PR DESCRIPTION
**Pull request by howardjohn**
motivation here is to add a presubmit for the docker build so we don't break things

### CODE REVIEW

**Comment by jasonwzm** [comment]
This could take ~40mins to run as a presubmit test?

**Comment by howardjohn** [comment]
We will just make it run only when its changed. I am working on something that will make it ~20min as well

**Comment by jasonwzm** [comment]
nit: Also have this as a `make` target, so it is easy to trigger.

**Pull request merged**
