### PR TITLE
add perf tests for authz dry-run

### PR DESCRIPTION
**Pull request by yangminzhu**
Note the dry-run perf test enables the telemetry stackdriver to better simulate the use case in real environment. 

cc @xulingqing @richardwxn

### CODE REVIEW

**Comment by yangminzhu** [comment]
@istio/wg-test-and-release-maintainers could someone help take a look the PR? Thanks.

**Comment by yangminzhu** [comment]
@istio/wg-test-and-release-maintainers ping

**Review by jacob-delgado — APPROVED** [review]
approved, but take a look at the benchmark_tools job and make sure it's fine before merging

**Comment by yangminzhu** [comment]
@jacob-delgado It seems the benchmark_check_tools has been already been failing for some other issues:

```
+ CMDs_ARR=('kubectl get crds/prometheuses.monitoring.coreos.com' 'kubectl get crds/alertmanagers.monitoring.coreos.com' 'kubectl get crds/podmonitors.monitoring.coreos.com' 'kubectl get crds/prometheusrules.monitoring.coreos.com' 'kubectl get crds/servicemonitors.monitoring.coreos.com')
+ for CMD in "${CMDs_ARR[@]}"
+ MAXRETRIES=0
+ kubectl get crds/prometheuses.monitoring.coreos.com
Error from server (NotFound): customresourcedefinitions.apiextensions.k8s.io "prometheuses.monitoring.coreos.com" not found

```

**Review by richardwxn — APPROVED** [review]

**Comment by richardwxn** [comment]
The benchmark job became flaky because of the prometheus issue, I haven't had time to fix that, but it is not relevant to this PR

**Pull request merged**
