### PR TITLE
Switch this repo to BUILD_WITH_CONTAINER=1

### PR DESCRIPTION
**Pull request by geeknoid**
- Update common files

- Fix python formatting so that python linting would pass.

### CODE REVIEW

**Comment by geeknoid** [comment]
Needs https://github.com/istio/test-infra/pull/1710 in order to pass CI.

**Comment by geeknoid** [comment]
Now needs https://github.com/istio/test-infra/pull/1711 for CI to pass.

**Comment by howardjohn** [comment]
all other builds seem broken until this is merged

**Pull request merged**
