### PR TITLE
better description render

### PR DESCRIPTION
**Pull request by zirain**
before:

image

after:

image

### CODE REVIEW

**Comment by ericvn** [comment]
Is there a way to verify this output? Trying to build an image and using that did not seem to cause any new changes and not sure where this came from.

**Comment by zirain** [comment]
> Is there a way to verify this output? Trying to build an image and using that did not seem to cause any new changes and not sure where this came from.

try this: https://github.com/zirain/playground/blob/master/istio/gen-annotations.md

**Review by ericvn — APPROVED** [review]
I notice several description renders fixed besides those shown here.  I did not see any regressions.

Thanks.

**Pull request merged**
