### PR TITLE
Update example benchmark CSV

### PR DESCRIPTION
**Pull request by carolynhu**
1. Optimize collect_metrics call, do not need to collect metrics every config run
2. Update graph plotter benchmark csv example file, since the old one missing cpu/mem data

### CODE REVIEW

**Review by howardjohn — COMMENTED** [review]
how does it know which timestamps to use if its not run per benchmark run? won't this give the same metrics for all the runs?

I think this applies to the before and after state

**Comment by carolynhu** [comment]
> how does it know which timestamps to use if its not run per benchmark run? won't this give the same metrics for all the runs?
> 
> I think this applies to the before and after state

(1) the timestamp recorded and saved in fortio/data https://github.com/istio/tools/blob/master/perf/benchmark/runner/fortio.py#L131
we only need to fetch once and generate the benchmark CSV file. 
(2) Since we have test_labels, which is prefixed by run_id, https://github.com/istio/tools/blob/master/perf/benchmark/runner/runner.py#L125 so different metrics will not interfered with each other

**Comment by howardjohn** [comment]
where is the actual prometheus query selecting only those? We query for CPU usage at some point, how do we make sure we get the CPU only for a specific test run and not the average cpu across all runs?

**Comment by carolynhu** [comment]
> where is the actual prometheus query selecting only those? We query for CPU usage at some point, how do we make sure we get the CPU only for a specific test run and not the average cpu across all runs?

i think your are right, with prometheus fetch: https://github.com/istio/tools/blob/master/perf/benchmark/runner/fortio.py#L170
we should run collect_metrics every time, unless we do some optimizations on promethues fetching part, but which is not in this PR's scope, i'm going to revert that commit. thanks!

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
