### PR TITLE
[release-1.16] Revert the skip-broken for Centos once upstream is fixed

### PR DESCRIPTION
**Pull request by ericvn**
This should fail the container test until upstream is fixed.

### CODE REVIEW

**Comment by ericvn** [comment]
DNM until branch step #5 is done.

**Comment by ericvn** [comment]
Upstream fix needed: https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2022-318362b0c0

**Review by dhawton — APPROVED** [review]

**Pull request merged**
