### PR TITLE
Update kubetest2 and gcloud to the latest version

### PR DESCRIPTION
**Pull request by chizhg**
1. Update `kubetest2` to fix a bug as described in kubernetes-sigs/kubetest2#75
2. Update `gcloud` to the latest version

The same as done in https://github.com/istio/tools/pull/1343

### CODE REVIEW

**Review by carolynhu — APPROVED** [review]

**Review by elfinhe — APPROVED** [review]

**Comment by chizhg** [comment]
The error for `lint_tools_release-1.7` seems to be unrelated..

```
xargs: helm: No such file or directory
common/Makefile.common.mk:36: recipe for target 'lint-helm' failed
make: *** [lint-helm] Error 127
```

**Comment by elfinhe** [comment]
> The error for `lint_tools_release-1.7` seems to be unrelated..
> 
> ```
> xargs: helm: No such file or directory
> common/Makefile.common.mk:36: recipe for target 'lint-helm' failed
> make: *** [lint-helm] Error 127
> ```

yep, lint issue is tracked by: https://github.com/istio/istio/issues/29065.

**Comment by chizhg** [comment]
> > The error for `lint_tools_release-1.7` seems to be unrelated..
> > ```
> > xargs: helm: No such file or directory
> > common/Makefile.common.mk:36: recipe for target 'lint-helm' failed
> > make: *** [lint-helm] Error 127
> > ```
> 
> yep, lint issue is tracked by: [istio/istio#29065](https://github.com/istio/istio/issues/29065).

Do we have a way to forcibly merge it? Or shall we wait for the next Automator update?

**Pull request merged**
