### PR TITLE
Tratis Tool

### PR DESCRIPTION
**Pull request by saimsalman36**
This is the new tool `Tratis` which would convert a trace output into a format that can be integrated with the configuration file for `Isotope`. This helps one in automatically generating a configuration file for an application instead of manually setting it up for `Isotope`.

Current Implementation:
  1. Currently only support Jaeger but as Jaeger tracing API follows that of [OpenTracing](https://opentracing.io/docs/supported-tracers/) Tratis can be easily extended to support any of the other distributed tracers supported by OpenTracing.
  2. Extracts the traces from the distributed tracer (Jaeger) and divides them into sets where each set of traces follows the same dependency graph.
  3. Extracts the n-ary dependency graph for each set.
  4. Collects all the timing, response + request size information and runs distribution fitting.
  5. The distribution fitting module is written in Python3 because of the availability of libraries in Python3.

(@richardwxn and @mandarjog : Updated the PR and addressed the comments). I've closed all the older PRs for tratis. Apologies for the delayed response.

### CODE REVIEW

**Comment by saimsalman36** [comment]
@richardwxn This PR consolidates all the Tratis related PRs. I've closed all of them. I haven't closed the non-Tratis related PRs.

**Comment by richardwxn** [comment]
not stale

**Comment by sdake** [comment]
@richardwxn is this PR still relevant?

**Comment by jacob-delgado** [comment]
This PR is over a year old with no progress. Closing. Feel free to reopen it if you want to make changes.

**Pull request closed without merging**
