### PR TITLE
Add istio-proxy CPU usages by pod_name into dashboard

### PR DESCRIPTION
**Pull request by carolynhu**
https://github.com/istio/istio/issues/25169

Presents as:
Screen Shot 2020-07-20 at 3 27 47 PM
Screen Shot 2020-07-20 at 3 26 59 PM

### CODE REVIEW

**Comment by carolynhu** [comment]
Any refactor will be done after all the new features merged in.

**Comment by carolynhu** [comment]
@mandarjog  @howardjohn please take a look

**Comment by howardjohn** [comment]
On the average CPU one, looks like the y Axis is wrong - it says `latency`?

**Comment by carolynhu** [comment]
oh, yeah, let me fix it!

**Pull request merged**
