### PR TITLE
Revert cue-gen move to v1, move back to v1beta1

### PR DESCRIPTION
**Pull request by joeyb**
This change partially reverts #1046. It is the first step of a series of PRs that will move back to using v1beta1 APIs to add back support for kubernetes 1.15.

### CODE REVIEW

**Comment by howardjohn** [comment]
Is it feasible to test the v1beta1 change E2E to ensure we can actually downgrade before we go through all of this effort?

**Comment by pnambiarsf** [comment]
@howardjohn - As discussed during the WG yesterday, it is not possible for us to validate before merging into master. We agreed that we could merge into master and rely on the CI to validate. Once we have all the PRs merged we can validate them together.

**Comment by jasonwzm** [comment]
Can you also change the unit test for it?

**Comment by jasonwzm** [comment]
Have you tried manually testing the CRD file?

**Comment by nikolay-pshenichny** [comment]
> Have you tried manually testing the CRD file?


@jasonwzm, are you referring to `kubectl apply -f customresourcedefinitions.gen.yaml` ?

```
$ kubectl apply -f customresourcedefinitions.gen.yaml
customresourcedefinition.apiextensions.k8s.io/destinationrules.networking.istio.io configured
customresourcedefinition.apiextensions.k8s.io/envoyfilters.networking.istio.io configured
customresourcedefinition.apiextensions.k8s.io/gateways.networking.istio.io configured
customresourcedefinition.apiextensions.k8s.io/serviceentries.networking.istio.io configured
customresourcedefinition.apiextensions.k8s.io/sidecars.networking.istio.io configured
customresourcedefinition.apiextensions.k8s.io/virtualservices.networking.istio.io configured
customresourcedefinition.apiextensions.k8s.io/workloadentries.networking.istio.io configured
customresourcedefinition.apiextensions.k8s.io/workloadgroups.networking.istio.io configured
customresourcedefinition.apiextensions.k8s.io/authorizationpolicies.security.istio.io configured
customresourcedefinition.apiextensions.k8s.io/peerauthentications.security.istio.io configured
customresourcedefinition.apiextensions.k8s.io/requestauthentications.security.istio.io configured
```


We also use the same `customresourcedefinitions.gen.yaml` (generated with the cue-gen built from this PR) in our fork/build of istio/istio for testing.

**Comment by jasonwzm** [comment]
You can copy the generated CRD file and copy over to istio/istio manifest and run some integration tests locally.

**Comment by nikolay-pshenichny** [comment]
> You can copy the generated CRD file and copy over to istio/istio manifest and run some integration tests locally.


@jasonwzm, we replaced all `crd-all.gen` files manually in this PR - https://github.com/istio/istio/pull/26587/files#diff-b35d9214247be09ead513d7a7048624a

`update_crds.sh` is temporary commented out to ensure that we are not pulling `v1` CRDs  - https://github.com/istio/istio/pull/26587/files

Could you please point out any tests that you would like us to run? Thank you!

**Comment by howardjohn** [comment]
We should do the testing asked in https://github.com/istio/istio/pull/26587#issuecomment-675608288 before merging, not after. Thanks!

**Pull request merged**
