### PR TITLE
Revert LLVM change

### PR DESCRIPTION
**Pull request by howardjohn**
This will break the proxy as it relies on the specific glibc version. The LLVM 404 issues seem transient

### CODE REVIEW

**Comment by jasonwzm** [comment]
Does 9.0.1 work for proxy? We can use LLVM's RHEL binary for the centos build.

**Comment by howardjohn** [comment]
There is nothing completely broken with the download, its just transient failures

**Comment by howardjohn** [comment]
I can download it manually

**Comment by jasonwzm** [comment]
9.0.1 does not have image for suse: https://releases.llvm.org/download.html#9.0.1 You probably want to use the rhel image.

**Pull request merged**
