### PR TITLE
add trialrun to run as presubmit

### PR DESCRIPTION
**Pull request by richardwxn**
dryrun only runs the setup cluster, fortio setup part, and installation part for different configs.

pending: need to add a check for fortio command error

### CODE REVIEW

**Comment by howardjohn** [comment]
This is not really a "dry run" which normally does not modify the cluster. Maybe call it `fast` or `trial` or `test` or something?

**Comment by richardwxn** [comment]
@howardjohn sure, done

**Comment by richardwxn** [comment]
added new entry script to be triggered from prow and run test only when benchmark related code updated

**Comment by richardwxn** [comment]
@howardjohn is it ok to check in this?

**Comment by carolynhu** [comment]
https://github.com/istio/istio/issues/22109

**Pull request merged**
