### PR TITLE
Saim Sleep Feature

### PR DESCRIPTION
**Pull request by saimsalman36**
Extended the sleep feature (of Isotope).

Instead of taking a simple static value, now, one can provide:

1. Distribution (Only those set of distributions that gonum supports)
2. Histogram
3. Static Value
4. Raw Data

Also, one can specify load-levels for the sleep-command. This allows one to emulate different sleep times for different load levels.

Examples: 
```yaml
sleep: {"SleepCommand": [{Load: {Min: 0, Max: 100}, type: "static", data: {time: "10ms"}}]}
```

```yaml
sleep: {"SleepCommand": [{Load: {Min: 0, Max: 100}, type: "static", data: {time: "10ms"}}, {Load: {Min: 101, Max: 200}, type: "static", data: {time: "20ms"}}]}
```

```yaml
sleep: {"SleepCommand": [{Load: {Min: 0, Max: 1000}, Type: "histogram", data: {"50ms": 50, "100ms": 50}}]}
```

```yaml
sleep: {"SleepCommand": [{Load: {Min: 0, Max: 1000}, Type: "dist", data: {name: "normal", Dist: {"Mu": 1.0, "Sigma": 0.25}}}]}
```

```yaml
sleep: {"SleepCommand": [{Load: {Min: 0, Max: 1000}, Type: "raw", data: {list: [1,2,3]}}]}
```

I've added the examples as well as details in the README.

### CODE REVIEW

**Comment by saimsalman36** [comment]
I've closed the other PRs related to the feature and added the updated code in this PR.

**Comment by saimsalman36** [comment]
@mandarjog lint-tools fails because of `common/Makefile.common.mk:61: recipe for target 'lint-licenses' failed`. I don't know how to fix this.

**Comment by sdake** [comment]
@geeknoid policy bot did something wrong here.  @saimsallsman a rebase will fix the linter errors.  We had some transient problems diring repo syncs.

**Pull request closed without merging**
