### PR TITLE
fix: graph plotter cpu and mem graph error

### PR DESCRIPTION
**Pull request by chinaran**
when graph_type in [cpu-client cpu-server mem-client mem-server]
the y_axis value should *1000

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Comment by chinaran** [comment]
@googlebot I fixed it.

**Comment by chinaran** [comment]
@googlebot I fixed it.

**Comment by chinaran** [comment]
@googlebot I fixed it.

**Review by ericvn — APPROVED** [review]

**Comment by chinaran** [comment]
@howardjohn @ericvn Do you know why this pr is blocked ? Thank you!

**Review by ericvn — APPROVED** [review]

**Comment by ericvn** [comment]
@chinaran Should be freed up (needs to run and pass tests).

**Comment by chinaran** [comment]
@ericvn thank you

**Pull request merged**
