### PR TITLE
Install tshark in istio proxy build tools

### PR DESCRIPTION
**Pull request by bianpengyuan**
After switch source of cmake to `apt.kitware.com`, proxy build fails because of missing `libxml2` library. Upstream Envoy build tools container downloads libxml2 with tshark pkg. This is to make istio container match that: https://github.com/envoyproxy/envoy-build-tools/blob/b1a8b205f13ce52143bcb7283c6dd0a53bcd1c6c/build_container/build_container_ubuntu.sh#L48

cc @lizan

### CODE REVIEW

**Review by carolynhu — APPROVED** [review]

**Comment by lizan** [comment]
This change LGTM, but it's unexpected to see we require libxml... what error have we seen?

**Comment by bianpengyuan** [comment]
@lizan This is one of the example failure: https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_proxy/3070/test-asan_proxy/1322241971502190592/build-log.txt

**Comment by lizan** [comment]
OK thanks, it's V8 :facepalm:

**Comment by kyessenov** [comment]
It would be really nice if v8 was bazelified... It's such PITA to build it over and over.

**Comment by bianpengyuan** [comment]
Looks like luajit also relies on it: https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_proxy/3070/release-test_proxy/1322309414786437120/build-log.txt

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
