### PR TITLE
[release-1.13] Update go to 1.17.11

### PR DESCRIPTION
**Pull request by jacob-delgado**

### CODE REVIEW

**Review by lei-tang — APPROVED** [review]

**Comment by jacob-delgado** [comment]
Looks like https://github.com/kubernetes/test-infra is dependent on Go 1.18

```
#81 [binary_tools_context 53/99] RUN git clone https://github.com/kubernetes/test-infra --branch master --single-branch &&   cd test-infra &&   git checkout "ae26658abae0b1213549d1326b3b252422fe0215" &&   go install ./robots/pr-creator &&   go install ./prow/cmd/peribolos &&   go install ./pkg/benchmarkjunit &&   cd .. && rm -rf test-infra
#82 16.87 # k8s.io/test-infra/prow/config/secret
#82 16.87 ../go/pkg/mod/k8s.io/test-infra@v0.0.0-20220608174622-2d1e39535abb/prow/config/secret/agent.go:73:19: syntax error: unexpected [, expecting (
#82 16.87 ../go/pkg/mod/k8s.io/test-infra@v0.0.0-20220608174622-2d1e39535abb/prow/config/secret/reloader.go:27:30: syntax error: unexpected any, expecting ]
#82 16.87 ../go/pkg/mod/k8s.io/test-infra@v0.0.0-20220608174622-2d1e39535abb/prow/config/secret/reloader.go:32:25: syntax error: unexpected (, expecting name or (
#82 16.87 ../go/pkg/mod/k8s.io/test-infra@v0.0.0-20220608174622-2d1e39535abb/prow/config/secret/reloader.go:33:1: syntax error: non-declaration statement outside function body
#82 16.87 ../go/pkg/mod/k8s.io/test-infra@v0.0.0-20220608174622-2d1e39535abb/prow/config/secret/reloader.go:35:31: syntax error: unexpected [, expecting comma or )
#82 16.87 ../go/pkg/mod/k8s.io/test-infra@v0.0.0-20220608174622-2d1e39535abb/prow/config/secret/reloader.go:50:31: syntax error: unexpected [, expecting comma or )
#82 16.87 ../go/pkg/mod/k8s.io/test-infra@v0.0.0-20220608174622-2d1e39535abb/prow/config/secret/reloader.go:52:2: syntax error: non-declaration statement outside function body
#82 16.87 ../go/pkg/mod/k8s.io/test-infra@v0.0.0-20220608174622-2d1e39535abb/prow/config/secret/reloader.go:89:31: syntax error: unexpected [, expecting comma or )
#82 16.87 ../go/pkg/mod/k8s.io/test-infra@v0.0.0-20220608174622-2d1e39535abb/prow/config/secret/reloader.go:95:31: syntax error: unexpected [, expecting comma or )
#82 16.87 ../go/pkg/mod/k8s.io/test-infra@v0.0.0-20220608174622-2d1e39535abb/prow/config/secret/secret.go:34:32: syntax error: unexpected [, expecting (
#82 16.87 ../go/pkg/mod/k8s.io/test-infra@v0.0.0-20220608174622-2d1e39535abb/prow/config/secret/secret.go:34:32: too many errors
#82 16.87 note: module requires Go 1.18

```

**Comment by howardjohn** [comment]
I don't get how that is possible , aren't we doing `git checkout
ae26658abae0b1213549d1326b3b252422fe0215`? How is it pulling from master?

**Pull request merged**
