### PR TITLE
update benchmark test nomixer and mixer label

### PR DESCRIPTION
**Pull request by carolynhu**
This PR intend to modify the existing test labels on the our perf graphs, like the below.
Screen Shot 2019-12-18 at 4 34 02 PM

Proposal: 
(1) add "mixer" before "serveronly" and "both"
(2) change "nomixer" to "envoy"

@mandarjog  @howardjohn Please discuss under this PR about your opinion on the above proposal.

### CODE REVIEW

**Comment by mandarjog** [comment]
I would like to harmonize all these names.  Mixer - no-mixer were errors :-) so we need to get rid of it.

Generally every option should state what it `includes` and not what it excludes.
examples:
`both:  mixer is deployed and there are 2 sidecars   - mixer-both`
`serveronly: mixer-serveronly`
`nomixer-*: envoy`

etc.

**Comment by mandarjog** [comment]
@richardwxn what do you think?

**Comment by richardwxn** [comment]
I think this one: "nomixer-*: envoy" is confusing. Also we are not using the term of mixerv2 anymore, right?

My suggestion is change the argument name to telemetry_mode, and for the options we have: mixer, envoy_native, telemetryv2" ?

**Comment by carolynhu** [comment]
@mandarjog  any feedback?

**Comment by mandarjog** [comment]
@richardwxn telemetry mode perhaps makes sense. We need to rationalize it though.
In our experiment modes are `none, mixer, v2`. We do not test with `envoy_native` since we disable all envoy native telemetry by default. We want to measure the cost of every feature we add, but also want to measure the cost of typical configurations.

how about `filters: none, native, mixer, v2, authz, authn, stackdriver` etc ... ?

**Comment by richardwxn** [comment]
@mandarjog yep that makes sense to me

**Comment by mandarjog** [comment]
Well, that did not work :-( I was too slow in adding do not merge.

**Comment by carolynhu** [comment]
@mandarjog I cannot change UI at the current stage, since the perf pipeline has no data related to the new labels. I will make a separate PR to make UI consistent with the new labels.

**Comment by carolynhu** [comment]
https://github.com/istio/istio/issues/19736

**Pull request merged**
