### PR TITLE
bump golangci-lint

### PR DESCRIPTION
**Pull request by zirain**
depguard upgrade to v2, see https://github.com/golangci/golangci-lint/pull/3795

### CODE REVIEW

**Review by howardjohn — COMMENTED** [review]
can you check that istio/istio update works? it has complex depguard usage

**Comment by ericvn** [comment]
As a note on how to do the testing, you can build a new build-tools image with `make containers-test`. You need to let it run long enough for it to create a new build-tools image of the form: ${HUB}/build-tools:master-latest-<architecture>. Then you can use this image to run the various `make` commands.

In this case, go to istio/istio and run something like `IMG=ericvn/build-tools:master-latest-amd64 make lint`.
This will cause a number of dep-guard errors.

You will need to understand that the golangci.yml from common-files gets updated with an override from the istio/istio/tools/golangci-override.yaml.

**Comment by zirain** [comment]
@howardjohn @ericvn 
create a test PR: https://github.com/istio/istio/pull/45300

**Review by howardjohn — APPROVED** [review]
ty!

**Pull request merged**
