### PR TITLE
Fix oneOf representation in doc and schema

### PR DESCRIPTION
**Pull request by jasonwzm**
fix: https://github.com/istio/istio/issues/22100

This will mark `oneOf` fields in docs as optional.
In schemas, the `oneOf` representation is changed to disjunction of required closed structs and an open struct. For example, `match` in `EnvoyFilter` is now:
```yaml
match:
  description: Match on listener/route configuration/cluster.
  oneOf:
  - not:
      anyOf:
      - required:
        - listener
      - required:
        - routeConfiguration
      - required:
        - cluster
  - required:
    - listener
  - required:
    - routeConfiguration
  - required:
    - cluster
  properties:
  ...
```

### CODE REVIEW

**Comment by howardjohn** [comment]
don't we need ot update cue in `tools` repo? Or whatever is doing the crd gen

**Comment by jasonwzm** [comment]
> don't we need ot update cue in `tools` repo? Or whatever is doing the crd gen

It updates `cue`. Cue has some api changes, I will push another commit to make the lint happy.

**Comment by howardjohn** [comment]
Should the crd.yaml change though?

**Comment by howardjohn** [comment]
oh I thought this was the API repo... I am lost

**Comment by jasonwzm** [comment]
> oh I thought this was the API repo... I am lost

Yes, I will update api repo once this merges.

**Pull request merged**
