### PR TITLE
improve resource annotation table UX

### PR DESCRIPTION
**Pull request by zirain**
xref: https://github.com/istio/istio.io/issues/14453
checkout preview in: https://github.com/istio/istio.io/issues/14453#issuecomment-1883253521

### CODE REVIEW

**Review by jacob-delgado — APPROVED** [review]
lgtm. approving, but putting on dnm/hold so others can have feedback

cc @linsun

**Review by linsun — APPROVED** [review]
Preview LG thanks @zirain !

Could you confirm this only changes the annotation table?

**Comment by zirain** [comment]
> Preview LG thanks @zirain !
> 
> Could you confirm this only changes the annotation table?

yeah, but I think the automater will fail, and give us a change to confirm.

**Comment by zirain** [comment]
@linsun it will also change labels page, which I think it's good.

image

**Pull request merged**
