### PR TITLE
Fix outdated addons

### PR DESCRIPTION
**Pull request by howardjohn**
- old Cert manager doesn't work on modern k8s versions
- prom image is not existing anymore. This was the biggest change, new operator doesn't install CRDs so we need to update things a bit

### CODE REVIEW

**Comment by howardjohn** [comment]
Job is 100% broken right now, so presumably this cannot be worse than the current state...

**Review by jacob-delgado — APPROVED** [review]

**Comment by ericvn** [comment]
#1807 doesn't appear to have fixed the underlying issue, and additional changes will be needed. A manual cherry-pick of those changes can be done at that time.

**Comment by zirain** [comment]
> #1807 doesn't appear to have fixed the underlying issue, and additional changes will be needed. Thus, we can ignore the thought of manually cherry-picking this PR now. A manual cherry-pick of all changes to fix the test failure can be done later.

let's try update https://perf.dashboard.istio.io/  after 1.13.0 released (should be tomorrow).

**Pull request merged**
