### PR TITLE
Add Nighthawk perf test configuration files and pipeline entry

### PR DESCRIPTION
**Pull request by carolynhu**

### CODE REVIEW

**Comment by carolynhu** [comment]
> I think most of the test setup, runtime and istio installation configs are shared between nighthawk and istio, so instead of duplicating them and changing only the load gen type, would it be better to use the shared part as base, and specify load gen type as a list to mutate with

yeah, i'm going to do that, since there is still one step left to make nighthawk work. I'm creating this to make it easier to test. Will make things simple and clean once I've done the test.

**Comment by carolynhu** [comment]
Put on hold...
the run_benchmark_job logic needs to handle env var LOAD_GEN_TYPE properly. I'm figuring out the better way to do it.

**Comment by dex80526** [comment]
@carolynhu: PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by carolynhu** [comment]
I'm going to close this PR, since it is resolved by https://github.com/istio/tools/pull/937 and https://github.com/istio/test-infra/pull/2644

**Pull request closed without merging**
