### PR TITLE
Remove 'stability' testing

### PR DESCRIPTION
**Pull request by howardjohn**
This was effectively abandonware, first introduced by myself as one of
my first projects on Istio 5 years ago (not to take credit for it all -
there have been a variety of contributions since then). We do not use it
as part of testing of Istio, nor is it maintained at all. I think
keeping it just causes confusion and bloats the repo.

Not we sometimes call the testing we do "stability" testing in speaking.
In terms of this repo, that is actually 'load' testing.

We have:
* Load - run a lot of stuff, and (poorly) check for perf issues
* benchmark - run 2 workloads and benchmark latency
* Stability - attempt to run real world scenarios and monitor them

The "stability" tests are basically replaced by standard e2e tests under
istio/istio.

### CODE REVIEW

**Comment by howardjohn** [comment]
cc @keithmattix

**Comment by keithmattix** [comment]
/cc @biefy @shalierxia

We probably want to replace these with more robust scale testing, but indeed, it's probably better to start from scratch here

**Comment by howardjohn** [comment]
cc @sergii-ssh

**Comment by howardjohn** [comment]
Seems like we are waiting for people to possibly object with no indication of "its ok". Are there any concerns or more time needed?

From discussion with @sergii-ssh offline it should be fine from their POV (with a change I already pushed up).

**Comment by jacob-delgado** [comment]
I'm fine with merging this. I'll approve and add a DNM/hold to it. Remove when you feel it's ok.

**Review by jacob-delgado — APPROVED** [review]

**Comment by howardjohn** [comment]
If we accidentally deleted too much, easy to add back :slightly_smiling_face:

**Pull request merged**
