### PR TITLE
markdown: move BlackFriday to goldmark

### PR DESCRIPTION
**Pull request by zirain**
fix: https://github.com/istio/istio/issues/41377

running `make containers-test`, got image `gcr.io/istio-testing/build-tools:master-latest-amd64`
then running `istio/api` with this image, everything looks good.

### CODE REVIEW

**Review by ericvn — APPROVED** [review]
Thanks.

**Comment by ericvn** [comment]
Looking into this change more I think we need to change the rendering option removing xhtml and breaks and add unsafe. Testing with that now.

**Comment by ericvn** [comment]
Above from looking at the istio.io config.tml

**Comment by ericvn** [comment]
Not necessarily sure why, but making the changes above did not reflect differently in the generated `make gen` output.

**Comment by ericvn** [comment]
Creating a simple program and running it:
```
package main

import (
	"bytes"
	"fmt"

	"github.com/yuin/goldmark"
	"github.com/yuin/goldmark/extension"
	"github.com/yuin/goldmark/parser"
	"github.com/yuin/goldmark/renderer/html"
)

func main() {
	var buf bytes.Buffer
	md := goldmark.New(
		goldmark.WithExtensions(extension.GFM),
		goldmark.WithParserOptions(
			parser.WithAutoHeadingID(),
		),
		goldmark.WithRendererOptions(
			html.WithUnsafe(),
		),
	)
	source := []byte("AnalysisMessageWeakSchema is the set of information \n that&rsquo;s needed to define a weakly-typed schema. \n The purpose of this proto is to provide a mechanism for validating \n istio/istio/galley/pkg/config/analysis/msg/messages.yaml to make sure that we \n don&rsquo;t allow committing underspecified types. \n {{<tab name=\"v1beta1\" category-value=\"v1beta1\">}}")
	if err := md.Convert(source, &buf); err != nil {
		panic(err)
	}
	fmt.Println(buf.String())
	return
}
```
seems to show a better output:
```
<p>AnalysisMessageWeakSchema is the set of information
that’s needed to define a weakly-typed schema.
The purpose of this proto is to provide a mechanism for validating
istio/istio/galley/pkg/config/analysis/msg/messages.yaml to make sure that we
don’t allow committing underspecified types.
{{<tab name="v1beta1" category-value="v1beta1">}}</p>
```
With the current code:
```
<p>AnalysisMessageWeakSchema is the set of information<br />
that’s needed to define a weakly-typed schema.<br />
The purpose of this proto is to provide a mechanism for validating<br />
istio/istio/galley/pkg/config/analysis/msg/messages.yaml to make sure that we<br />
don’t allow committing underspecified types.<br />
{{<!-- raw HTML omitted -->}}</p>
```
which shows the two differences.

**Comment by zirain** [comment]
I will take a look

**Pull request merged**
