### PR TITLE
[release-1.9] Update go-junit-report to the new commit

### PR DESCRIPTION
**Pull request by chizhg**
This is a manual cherry-pick of #1768

### CODE REVIEW

**Comment by jacob-delgado** [comment]
Release 1.9 has been EOL. Is there a reason why this was backported?

**Comment by chizhg** [comment]
I reconsidered about it and we actually don't need it. Will close this PR.

**Comment by chizhg** [comment]
@jacob-delgado it turns out we still want this change since 1.9 is still supported at Google. Is it fine to merge this change?

**Comment by jacob-delgado** [comment]
> since 1.9 is still supported at G

I'm ok with this, but I'll have @stevenctl approve of this since it's a Google need.

**Review by stevenctl — APPROVED** [review]

**Pull request merged**
