### PR TITLE
Update default.yaml to default-overlay.yaml to avoid confusion and remove deprecated field

### PR DESCRIPTION
**Pull request by carolynhu**
For fixing:https://storage.googleapis.com/istio-prow/logs/daily-fortio-performance-benchmark/8/build-log.txt

Ref: https://github.com/istio/istio/blob/master/manifests/profiles/default.yaml

### CODE REVIEW

**Comment by richardwxn** [comment]
@carolynhu also seems like what you did for 1.6 @carolynhu was not correct as well, please revert that and make change correspondingly

**Comment by carolynhu** [comment]
> you don't need to change everything in this default.yaml to align with the default profile in istio/istio, this default.yaml is just overlay on top of that, just specify what we need to customize for the perf run and don't copy everything over to here, e.g. no need to change customized resource settings, no need to change the hub and tag(otherwise you are not testing with what we want to test), remove the settings which are the same as default profile unless you want to explicitly emphasize it

I thought we were using this to install the default profile. Ok, let me update it. Thanks for letting me know.

**Comment by richardwxn** [comment]
yep I think changing the name would helps to avoid confusion. There are some other places but I can't remember exactly, you can do a search in the repo

**Comment by carolynhu** [comment]
@richardwxn fixed, please take a look

**Pull request merged**
