### PR TITLE
Enable strict mode.

### PR DESCRIPTION
**Pull request by geeknoid**

### CODE REVIEW

**Comment by howardjohn** [comment]
I have heard to mention in the past that you don't care if a human or mergify does the merging, if a human is faster then that is fine, mergify and people have the same permissions.

This model kind of breaks with `strict: true` -- now mergify will not merge a PR even though it meets all criteria for a human to merge.

Also, did we ever figure out if it will automatically rebase or must be done manually?

**Comment by geeknoid** [comment]
@howardjohn This mergify option needs to be combined with the equivalent GitHub option. Once both are in strict mode, then neither human nor Mergify can merge stuff in unless the repo is fully up to date.

Mergify will rebase itself. It needs to have write access to the author's repo in order to do this.

**Comment by howardjohn** [comment]
I would imagine this would effectively kill new contributors in istio/istio. New contributors aren't going to have mergify write access (either because it's more work or because it's not at all standard to allow someone write access to your fork to contribute to a project) meaning they will need to manually rebase 10-20x a day.

For this repo I don't care, but for the main one I really think mergify will be a large step backwards from tide.

**Comment by geeknoid** [comment]
Sadly, we can't use mergify's strict mode as it conflicts with the CLA bot. When mergify rebases before a commit, the CLA bot thinks a non-CLAed user has made a change.

**Pull request closed without merging**
