### PR TITLE
Improve Isotope Converter Usability

### PR DESCRIPTION
**Pull request by therealmitchconnors**
* Added Vendor directory as per dep guidelines (vendor/* files can be ignored in review)
* Improved README
* Improved HELP
* Write output to stdout instead of output file to improve scriptability

### CODE REVIEW

**Comment by mandarjog** [comment]
@therealmitchconnors Can you split this into 2 PRs.

PR1. Add vendoring and nothing else.
PR2. your 2nd commit ?

Does this also add command to generate the yaml artifacts without running them?

**Comment by therealmitchconnors** [comment]
Vendor changes moved to https://github.com/istio/tools/pull/120 . I *think* they will disappear from here once that PR is approved...

There has always been (afaik) a `convert kubernetes` command, which generates k8s resources but does not run them.  The Python runner does run the resources, and I have not added an option to generate python runner resources without running them, as they are pretty tightly coupled to GCP concepts which cannot be expressed as K8s resources...

This PR focused on making the convert command more usable, with the only python change being the way it calls the convert command...

**Comment by therealmitchconnors** [comment]
@mandarjog any further changes needed here?

**Comment by therealmitchconnors** [comment]
@mandarjog friendly ping

**Pull request merged**
