### PR TITLE
Add ytt to docker image

### PR DESCRIPTION
**Pull request by jacob-delgado**
There is a series of transforms that could make managing test-infra easier

### CODE REVIEW

**Comment by howardjohn** [comment]
can you elaborate more on what we are trying to do? it seems like we have a lot of yaml manipulation tools already... like more than 5

**Comment by jtischer-acasi** [comment]
> can you elaborate more on what we are trying to do? it seems like we have a lot of yaml manipulation tools already... like more than 5

If you are unfamiliar with YTT it is a nice tool for merging and altering yaml, we are using it to alter prow resource deployments and will be using it for altering jobs instead of adding more complexity to prowtrans & prowgen.

**Comment by howardjohn** [comment]
> > can you elaborate more on what we are trying to do? it seems like we have a lot of yaml manipulation tools already... like more than 5
> 
> If you are unfamiliar with YTT it is a nice tool for merging and altering yaml, we are using it to alter prow resource deployments and will be using it for altering jobs instead of adding more complexity to prowtrans & prowgen.

My concern is not that YTT is nice or not, but that we already have 5+ tools that are nice for transforming YAML, and unless the problem cannot be solved with those existing tools I am hesitant to add more

**Comment by jjtischer** [comment]
> > > can you elaborate more on what we are trying to do? it seems like we have a lot of yaml manipulation tools already... like more than 5
> > 
> > 
> > If you are unfamiliar with YTT it is a nice tool for merging and altering yaml, we are using it to alter prow resource deployments and will be using it for altering jobs instead of adding more complexity to prowtrans & prowgen.
> 
> My concern is not that YTT is nice or not, but that we already have 5+ tools that are nice for transforming YAML, and unless the problem cannot be solved with those existing tools I am hesitant to add more

First off, thank you and I agree with your validation questions. We don't just want to add tools and future debt for the sake of a new shiny toy. My apologies for not researching all the YAML tools that are pre-existing. It is not clear what/where all the YAML tools are could you please help me identify the ones you are aware of? Perhaps we should close this PR and create a research story in order to consolidate these tools.

@ericvn 

What are the 5+ tools? (here is what I have found)
- prowtrans
- prowgen
- YQ
- yamllint
- pyyaml

**Comment by howardjohn** [comment]
Also helm, jsonnet, kustomize, kpt

**Comment by jacob-delgado** [comment]
There are various types of tools used within the project to modify yaml.

1. istio/istio uses a variety of tools/libraries to manipulate yaml (helm, helm libraries, kustomize)
2. istio/api uses tools to generate various definitions (kpt?)
3. istio/test-infra uses tools to manipulate yaml to build istio (prowgen, prowtrans, yq)
4. istio/istio.io uses tools to render docs (this one i'm not entirely sure about)

IMO, #3 is an entirely different use case than #1 and #2. However, there isn't a way to include a tool such as YTT only for the purposes of `test-infra` at the moment; I'm not sure there should be either.

Cleanup of #3 is what this issue should reference. It's hard for T&R maintainers to be modify and keep track of presets, jobs, etc.. when there is so much manipulation going on. The differences in jobs as well as the different types of clusters and orgs (istio and istio-private) make it tedious. @jtischer-acasi has found many areas where things are being duplicated and places where github tokens are used and others where netrc is used. It's all very confusing and not welcoming to people willing to contribute to test-infra, which is severely lacking anyway.

@jtischer-acasi what does ytt do that the other tools do not do?

**Comment by jjtischer** [comment]
> 

YTT makes merging, updating, and removing complex yaml simple and easy to manage in a single place. No custom coding & testing just write some yaml overlays that will get applied to yaml to produce the output that you expect.

In helm templates: a deployment.yaml has template tags that get rendered into final yaml
In YTT: a deployment.yaml is normal and has all its default values as is. An overlay that contains the instructions via annotations is given to override/replace existing yaml making it more repeatable. 

This is really useful as changes can be stored together in separate folders very similar to prowgen but without the need to write each customization. YTT reduces needs to customize prowgen. I think there is future opportunity to reduce complexity in prowgen/prowtrans and move "straight forward" changes into YTT and leave the more complex business logic changes in prowgen/prowtrans. This would help reduce prowgen's responsibilities and be easier to use.

**Pull request closed without merging**
